# Configuración general de Spring
spring.application.name=eureka-service
# server.port=8761 # Se establece desde bootstrap.properties

# Configuración de Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuracion Actuador
# management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# management.endpoints.web.base-path=/manage