# Configuración general de Spring
spring.application.name=gateway-service
server.port=9090

# Configuracion Actuador
# management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# management.endpoints.web.base-path=/manage

# Configuracón Spring Security
spring.security.user.name=${SECURITY_USER}
spring.security.user.password=${SECURITY_PASSWORD}

# Configuración de Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://${ES_HOST}:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.uuid}

# Configuratión automatica de Gateway
# spring.cloud.gateway.discovery.locator.enabled=true
# spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Configuratión manual de Gateway
spring.cloud.loadbalancer.ribbon.enabled=false

spring.cloud.gateway.routes[0].id=razas
spring.cloud.gateway.routes[0].uri=lb://MICROSERVICIO-RAZAS
spring.cloud.gateway.routes[0].predicates[0]=Path=/razas/**, /api/razas/**

spring.cloud.gateway.routes[1].id=articulos
spring.cloud.gateway.routes[1].uri=lb://MICROSERVICIO-ARTICULOS
spring.cloud.gateway.routes[1].predicates[0]=Path=/articulos/**, /api/articulos/**, /articulos/**

spring.cloud.gateway.routes[2].id=conejos
spring.cloud.gateway.routes[2].uri=lb://CONEJOMONTANACIMIENTO
spring.cloud.gateway.routes[2].predicates[0]=Path=/, /conejos/**, /montas/**, /nacimientos/**, /ventas/**, /disponible/**, /api/**, /disponibles/**, /home/**

# Configuracion para endpoints
# spring.cloud.gateway.forwarded.enabled=true
# spring.cloud.gateway.x-forwarded.enabled=true

# spring.cloud.gateway.default-filters[0]=AddRequestHeader=X-Forwarded-Host, localhost
# spring.cloud.gateway.default-filters[1]=AddRequestHeader=X-Forwarded-Port, 8080
# spring.cloud.gateway.default-filters[2]=AddRequestHeader=X-Forwarded-Proto, http
