spring.application.name=gateway-service
server.port=9090

# Configuración general de Spring
# spring.application.name=gateway-service
# server.port=9090 # Se establece desde bootstrap.properties
# server.port=8080

# Configuración de la base de datos
# spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.hibernate.ddl-auto=${VALOR_DDL}
# spring.jpa.show-sql=true

# Configuracion Actuador
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# management.endpoints.web.exposure.include=health,info,prometheus,metrics
# management.endpoints.web.exposure.include=health
# management.endpoint.health.show-details=never
# management.endpoints.web.base-path=/manage

# Configuracón Spring Security
# spring.security.user.name=${SECURITY_USER}
# spring.security.user.password=${SECURITY_PASSWORD}

# Database configuration
# spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.hibernate.ddl-auto=${VALOR_DDL}
# spring.jpa.show-sql=true

# Configuración de Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://${ES_HOST}:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.uuid}

# Configuratión automatica de Gateway
# spring.cloud.gateway.discovery.locator.enabled=true
# spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Configuratión manual de Gateway
spring.cloud.loadbalancer.ribbon.enabled=false

spring.cloud.gateway.routes[0].id=razas
spring.cloud.gateway.routes[0].uri=lb://MICROSERVICIO-RAZAS
spring.cloud.gateway.routes[0].predicates[0]=Path=/razas/**, /api/razas/**

spring.cloud.gateway.routes[1].id=articulos
spring.cloud.gateway.routes[1].uri=lb://MICROSERVICIO-ARTICULOS
spring.cloud.gateway.routes[1].predicates[0]=Path=/articulos/**, /api/articulos/**

spring.cloud.gateway.routes[2].id=conejos
spring.cloud.gateway.routes[2].uri=lb://CONEJOMONTANACIMIENTO
spring.cloud.gateway.routes[2].predicates[0]=Path=/, /conejos/**, /montas/**, /nacimientos/**, /ventas/**, /disponible/**, /api/**, /*.css, /js/**

spring.cloud.gateway.routes[3].id=auth-service
spring.cloud.gateway.routes[3].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/auth/**

# Configuracion para endpoints
# spring.cloud.gateway.forwarded.enabled=true
# spring.cloud.gateway.x-forwarded.enabled=true

# spring.cloud.gateway.default-filters[0]=AddRequestHeader=X-Forwarded-Host, localhost
# spring.cloud.gateway.default-filters[1]=AddRequestHeader=X-Forwarded-Port, 8080
# spring.cloud.gateway.default-filters[2]=AddRequestHeader=X-Forwarded-Proto, http

# Loaded config data for profile 'dev'
logging.level.org.springframework.boot.context.config=DEBUG